### ISSUE TITLE
Add some notes about codespace options

### ISSUE THREAD

**Issue by hturner** [r-devel/r-dev-env#26]
We should add a few notes about this screenshot: https://github.com/r-devel/r-dev-env/blob/main/README.md?plain=1#L19. Actually, we will need to go back a bit to the line before the screenshot:

Click on the 'Open in GitHub Codespaces' button to bring up the codespace setup screen:
[screenshot]
You will see the message "Codespace usage for this repository is paid for by <username>", with your username. Don't panic! GitHub offers 120 hours codespace usage for free, you can check your allowance under "Codespaces" on https://github.com/settings/billing. You may want to select a region closer to you than the the default - leave the other options as they are and then click the green 'Create Codespace' button.

**Comment by jamestripp** [comment]
Codespace offers 120 core hours for free. The devcontainer uses 4 cores by default so that would be 30 hours (see https://github.com/features/codespaces).

The test could be changed (changes in bold) to:

You will see the message "Codespace usage for this repository is paid for by ", with your username. Don't panic! GitHub offers 120 **core** hours codespace usage for free, you can check your allowance under "Codespaces" on https://github.com/settings/billing. **The codespace for this repository defaults to 4 cores which gives you 30 hours for free.** You may want to select a region closer to you than the the default - leave the other options as they are and then click the green 'Create Codespace' button.
